### PR TITLE
nbval v0.10.0 with python pins

### PR DESCRIPTION
**Pull request by hoxbro**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #11

### CODE REVIEW

**Comment by hoxbro** [comment]
@conda-forge-admin, please rerender

**Comment by hoxbro** [comment]
@kain88-de and @takluyver, this should be ready for merging.

**Comment by hoxbro** [comment]
@ocefpaf, I'm really sorry to bother you, but do you have any guidance here?

**Comment by ocefpaf** [comment]
@Hoxbro this package could use more maintainers. If you are feeling adventurous please add yourself using https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-user-username.

**Pull request merged**
